### ISSUE TITLE
Copy from S3 to Azure doesn't respect destination path

### ISSUE THREAD

**Issue by andrewconnell** [kpfaulkner/azurecopy-go#3]
Trying to copy all the contents from an S3 container to a subfolder within an Azure blob container. While the log messages seem to say it understands what I told it, as the copy progresses, I'm seeing everything placed in the root of the Azure container.

Appears I have everything correct, but not giving the intended result. What I'm seeing that doesn't seem correct:

- the logs report it is copying the file into `folder1`, but in reality it's landing in the root of the container
  - *I've tried making sure `folder1` was both (a) present and (b) missing to let the tool create it (since there really is no creation of folders within blobs)... neither option had any effect*
- the copy operation is completely ignoring the 2nd folder I want to put it in

Why am I using a folder structure like that? The app in my NAS that does the nightly backup to Azure requires it. I'm trying to prime the backup so I don't have to reupload everything and instead rely on AWS' and Azure's much bigger pipes.

Here's a copy of what I ran & the resulting log. Goal is to take contents in the S3 bucket `https://s3.amazonaws.com/bucket-redacted/` and put them in the following path in Azure: `https://accountredacted.blob.core.windows.net/rivercity-nas0/folder1-redacted/folder2-redacted/`
  
```
C:\Users\acdev\Downloads
azurecopycommand_windows_amd64.exe -S3SourceAccessID="..." -S3SourceAccessSecret="..." -S3SourceRegion="us-east-1" -AzureDestAccountKey="..." -AzureDestAccountName="accountredacted" -source="https://s3.amazonaws.com/bucket-redacted/" -dest="https://accountredacted.blob.core.windows.net/container-redacted/folder1-redacted/folder2-redacted/" -copyblob
time="2017-02-25T07:17:32-05:00" level=info msg="&{<nil> 0xc042039080 <nil> <nil> 0xc042134420 <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}"
copy from https://s3.amazonaws.com/bucket-redacted/ to https://accountredacted.blob.core.windows.net/container-redacted/folder1-redacted/folder2-redacted/
Copying ._.DS_Store to folder1-redacted/._.DS_Store
Copying ._.apdisk to folder1-redacted/._.apdisk
Copying ._2014.06 - dotNetConf to folder1-redacted/._2014.06 - dotNetConf
Copying .DS_Store to folder1-redacted/.DS_Store
Copying ._.TemporaryItems to folder1-redacted/._.TemporaryItems
Copying .apdisk to folder1-redacted/.apdisk
Copying __db.001 to folder1-redacted/.AppleDB/__db.001
Copying __db.002 to folder1-redacted/.AppleDB/__db.002
Copying __db.003 to folder1-redacted/.AppleDB/__db.003
Copying __db.004 to folder1-redacted/.AppleDB/__db.004
Copying cnid2.db to folder1-redacted/.AppleDB/cnid2.db
Copying ._folders.501 to folder1-redacted/.TemporaryItems/._folders.501
Copying EC303_Quick.ppt to folder1-redacted/2006.03 - OfficeDevCon 2006/EC303_Quick.ppt
Copying Thumbs.db to folder1-redacted/2006.03 - OfficeDevCon 2006/Thumbs.db
Copying MRH-WebCM.ppt to folder1-redacted/2006.03 - OfficeDevCon 2006/WCM (Mark Harrison)/MRH-WebCM.ppt
Copying Readme.txt to folder1-redacted/2006.03 - OfficeDevCon 2006/WCM (Mark Harrison)/Readme.txt
Copying Thumbs.db to folder1-redacted/2006.03 - OfficeDevCon 2006/WCM (Mark Harrison)/Thumbs.db
```

**Comment by kpfaulkner** [comment]
Thankyou for the repro steps, investigating this morning

**Comment by kpfaulkner** [comment]
Can you repeat the command with the -debug flag and paste the output.

Thanks

**Comment by kpfaulkner** [comment]
Can you please try the [0.2.3](https://github.com/kpfaulkner/azurecopy-go/releases/tag/0.2.3) release and let me know how it goes?

Thanks

**Comment by andrewconnell** [comment]
That fixed it... although the resulting folder is forced to lowercase. For instance, in the example I gave above, my target is: `https://accountredacted.blob.core.windows.net/rivercity-nas0/conferences/Conferences/` (note the case of the second folder). The resulting structure is `/conferences/conferences/`.

I know... don't ask why I have the same name twice. It's an aspect of the NAS backup app.

**Comment by kpfaulkner** [comment]
Glad it worked! Will look into why the case changed.
