### ISSUE TITLE
Case of blob prefix converted to lower

### ISSUE THREAD

**Issue by kpfaulkner** [kpfaulkner/azurecopy-go#4]
When having a blob prefix with capitals, somewhere in the process it gets converted to lowercase.

**Comment by kevindente** [comment]
I think I might be hitting this issue. Will this prevent copying a "folder" in a container with an uppercase name (in my case, from Azure to S3)? If I copy from the root instead of specifying a subfolder, will uppercase folders be copied successfully?

**Comment by kpfaulkner** [comment]
I'd expect copying without a prefix would avoid this problem. I'll try and get a fix out for this soon (had put this issue on the back burner, but will have a snoop now)

**Comment by kpfaulkner** [comment]
Please try 0.3.2.

https://github.com/kpfaulkner/azurecopy-go/releases/tag/v0.3.2

**Comment by kevindente** [comment]
Works great! Thanks! Great tool!
