### ISSUE TITLE
Ignore Inheriting Source Path in Destination Path

### ISSUE THREAD

**Issue by darcy-railip** [kpfaulkner/azurecopy-go#6]
I've noticed that when I'm copying from a S3 source to an Azure destination that the destination blob ends up inheriting the S3 source path as well as the specified destination path.

Specifically, if I do this:

Source: .../bucket/A/B/folderToMove/[content]
Destination: /container/D/E/moveIntoHere

My files end up at:

/container/D/E/moveIntoHere/A/B/[content]

Is there any way to specifically have it end up at:

/container/D/E/moveIntoHere/[content]

Here is my current command, keys excluded:

./azurecopy -S3SourceAccessID="xxx" -S3SourceAccessSecret="xxx" -S3SourceRegion="us-east-1" -AzureDestAccountKey="xxx" -AzureDestAccountName="account" -source="https://s3.amazonaws.com/bucket/projects/56d46edc79aadb14008b4568/uploads/" -dest="https://account.blob.core.windows.net/container/projects/56d46edc79aadb14008b4568/versions/56d46edc79aadb14008b4569/source-files/58b4f7aaacad8513008b4567/master/" -copyblob

**Comment by kpfaulkner** [comment]
The "problem" here is that don't forget with S3 and Azure that the blobs name is actually "A/B/folderToMove/" and that the slashes are just "fake" ways of simulating directories. I'm working on being able to prune those at the moment. I'll update this issue when completed.

**Comment by darcy-railip** [comment]
Great. In the meantime, I suppose I could run a rename command on the source path such that it's the destination path that I'll eventually want, and then run it and set the destination path as simply the azure container name. Would that make sense?

**Comment by kpfaulkner** [comment]
Want to give 0.3.0 a spin? I think all the kinks are ironed out and should do exactly what you want (again, currently this version is only targeting S3 and Azure).

Please let me know if it fixes the problem for you.

https://github.com/kpfaulkner/azurecopy-go/releases/tag/0.3.0

**Comment by darcy-railip** [comment]
Works perfect! Thanks Ken, love the turnaround time. I'll let you close this in case you want to keep it open for non-S3/Azure versions.
