### ISSUE TITLE
AuthenticationFailed: Copy blob from one azure account container to another azure account container

### ISSUE THREAD

**Issue by RaghavendraP** [kpfaulkner/azurecopy-go#8]
Hi,

I am trying to copy a blob from one storage account to another storage account using the available release and getting AuthenticationFailed error. 

My command is: 
roles/copy-backup/files/azurecopycommand_linux_amd64 -copyblob -AzureSourceAccountKey <source-accountkey> -AzureSourceAccountName <source-accountname> -AzureDestAccountKey <dest-accountkey> -AzureDestAccountName <dest-accountname> -dest https://<dest-accountname>.blob.core.windows.net/<dest-container>/ -source https://<source-accountname>.blob.core.windows.net/<source-container>/<source-blob>/ -list -createcontainer true

ERRO[0000] Unable to copy  storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:000000
Time:2018-09-18T16:56:46.3742027Z, RequestId=000000, QueryParameterName=, QueryParameterValue=

Instead of direct azure to azure, if I copy the blob from azure to s3 and then from s3 to azure its working fine. So, there should not be any problem with credentials and access. Can you please let me know if there is any other configuration that is missing.

Thanks.

**Comment by kpfaulkner** [comment]
Hi

Which version of azurecopy are you using?

Also, is that literally the command you're using? Since you're specifying some arguments but are not supplying keys/names. For example the parameters should look something like:

-copy -dest="https://destacct.blob.core.windows.net/mycontainer/" -AzureSourceAccountName="srcacct" -AzureSourceAccountKey="xyxyxyxyxyxmykeyyxyxyxyxyx" -AzureDestAccountName="destacct" -AzureDestAccountKey="xyxyxyxmyotherkeyxyxyxyx" -source="https://srcacct.blob.core.windows.net/temp/"

The command you're trying doesn't have the keys or names. Also, you're telling it to list the contents (indicated by -list) but also copy. Please just try -copy for now.

If you can try again with the various keys/names in place and let me know how you go. If you still have issues, can you copy/paste the exact command you used (but replace the real keys with some other text)

Thanks

Ken

**Comment by RaghavendraP** [comment]
Hi Ken,

I am using version 0.2.2 and it seems old. I will try with latest version also will check without list option.

Previously I have entered the names and keys between '<' and '>'  and didn't realize that they are not appearing. 

The command which I am trying is:
azurecopycommand_linux_amd64 -copyblob -AzureSourceAccountKey "sourceaccountkey" -AzureSourceAccountName "sourceaccountname" -AzureDestAccountKey "destaccountkey" -AzureDestAccountName "destaccountname" -dest https://"destaccountname".blob.core.windows.net/"destcontainer"/ -source https://"sourceaccountname".blob.core.windows.net/"sourcecontainer"/"sourceblob"/ -list -createcontainer true

**Comment by RaghavendraP** [comment]
Hi,

I have downloaded version 0.3.2 and tried the following command with and without '-list' but still getting error: 

> ERRO[0000] Unable to copy  storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:

azurecopycommand_linux_amd64 -copyblob -AzureSourceAccountKey="sourcekey" -AzureSourceAccountName="sourceaccountname" -AzureDestAccountKey="destkey" -AzureDestAccountName="destaccountname" -dest="https://destaccountname.blob.core.windows.net/destcontainer/" -source="https://srcaccountname.blob.core.windows.net/sourcecontainer/sourceblob/" -createcontainer true

**Comment by kpfaulkner** [comment]
Hi

You're still trying to copy and create a container called "true".
Remove the -copyblob and "-createcontainer true" and just have -copy     and let me know how that goes.

Thanks

Ken

**Comment by RaghavendraP** [comment]
Hi Ken,

Without "-copyblob" option its working fine and the version I am using is 0.3.3. Thanks for the help.

Can you tell me the command on how to build your repo in my local with latest changes? as it seems there are some changes with respect to go azure library after 0.3.3.

Thanks,
Raghavendra.

**Comment by kpfaulkner** [comment]
Hi

Glad to hear it's working!!!

I'd suggest dont grab the latest source just yet. The Azure Go team have recently changed blob storage library. I've just finished migrating to the new lib (so far so good) but I'd wait a little while until those changes are fully tested.

But, if you really want to give it a go, going into azurecopycommand directory and running the usual: go build ./... will work.  Prior to that you'll probably need to run a go get on:

github.com/Sirupsen/logrus
github.com/satori/uuid
github.com/azure/azure-storage-blob-go/2016-05-31/azblob
github.com/dropbox/dropbox-sdk-go-unofficial/dropbox
github.com/aws/aws-sdk-go/aws

Thanks

Ken

**Comment by RaghavendraP** [comment]
Thanks for the fast help. Greatly appreciated. 💯
